- name: disable the module
  ansible.builtin.shell: dnf module disable redis -y
- name: enable the module
  ansible.builtin.shell: dnf module enable redis:7 -y
- name: install the redis
  ansible.builtin.dnf:
    name: redis
    state: installed
- name: Replace text
  ansible.builtin.replace:
    path: /etc/redis/redis.conf
    regexp: 127.0.0.1 
    replace: 0.0.0.0          
- name: protected module
  ansible.builtin.replace:
    path: /etc/redis/redis.conf
    regexp: 'protected-mode yes'
    replace: 'protected-mode no' 
- name: Enable service redis and ensure it is not masked
  ansible.builtin.systemd_service:
    name: redis
    state: restarted
    enabled: true         
    