- name: Copy the file from mongodb
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo
- name: Install the of mongo
  ansible.builtin.dnf:
    name: mongodb-org
    state: installed 
- name: Replace text
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: 127.0.0.1 
    replace: 0.0.0.0       
- name: Enable service httpd and ensure it is not masked
  ansible.builtin.systemd_service:
    name: mongod
    state: restarted
    enabled: true     