- name: disable the nignx
  ansible.builtin.shell: dnf module disable nginx -y
- name: enable the nginx
  ansible.builtin.shell: dnf module enable nginx:1.24 -y
- name: Install the latest version of nginx
  ansible.builtin.dnf:
    name: nginx
    state: installed
- name: Copy the file from nginx
  ansible.builtin.copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
- name: Recursively remove directory
  ansible.builtin.file:
    path: /usr/share/nginx/html/
    state: absent 
- name: create a directory
  ansible.builtin.file:
    path: /usr/share/nginx/html/
    state: directory
- name: download and extract 
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/frontend-v3.zip
    dest: /usr/share/nginx/html/
    remote_src: yes 
- name: Enable service httpd and ensure it is not masked
  ansible.builtin.systemd_service:
    name: nginx
    state: restarted
    enabled: true               

    

  