- name: import nodejs
  include_role:
    name: commmon
    tasks_from: nodejs
- name: copy the file to the mongo mongo.repo
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo
